<%@ page contentType="text/html;charset=UTF-8" %><%@ page import="java.util.*,java.text.SimpleDateFormat,com.lankawings.model.Ticket,com.lankawings.model.Booking" %>
<!doctype html><html lang="en"><head><title>Ticket Admin | Lanka Wings</title><%@ include file="/WEB-INF/jspf/head.jspf" %></head><body class="app-page"><%@ include file="/WEB-INF/jspf/header.jspf" %>
<main class="container page-pad">
  <div class="page-title reveal"><span class="eyebrow navy">TICKET ADMINISTRATION</span><h1>Admin ticket panel</h1></div>
  <%if(err!=null){%><div class="alert error"><%=h(err)%></div><%}%>
  <section class="stats-grid"><div class="stat-card"><span>Total reservations</span><strong data-count="<%=request.getAttribute("reservationCount")%>">0</strong><small>Ticket-reservation records</small></div><div class="stat-card"><span>Issued tickets</span><strong data-count="<%=request.getAttribute("ticketCount")%>">0</strong><small>Current ticket documents</small></div></section>
  <div class="toolbar"><input type="search" placeholder="Search ticket, PNR, passenger, flight or seat..." data-filter="#adminTicketBody" data-filter-item="tr"></div>
  <div class="table-wrap panel"><table><thead><tr><th>Ticket No.</th><th>PNR</th><th>Passenger</th><th>Flight</th><th>Seat</th><th>Status</th><th>Issued</th><th>Actions</th></tr></thead><tbody id="adminTicketBody">
  <%List<Ticket>ts=(List<Ticket>)request.getAttribute("tickets");Map<Integer,Booking>bm=(Map<Integer,Booking>)request.getAttribute("ticketBookings");SimpleDateFormat df=new SimpleDateFormat("dd MMM yyyy, HH:mm");boolean any=false;if(ts!=null){for(Ticket t:ts){Booking b=bm==null?null:bm.get(t.getBookingId());if(b==null)continue;any=true;%>
  <tr><td><b><%=h(t.getTicketNumber())%></b></td><td><%=h(b.getPnr())%></td><td><%=h(b.getPassengerName())%><br><small><%=h(b.getPassportNo())%></small></td><td><%=h(b.getFlightNo())%><br><small><%=h(b.getOrigin())%> → <%=h(b.getDestination())%></small></td><td><b><%=h(b.getSeatNumber())%></b></td><td><span class="badge"><%=h(t.getTicketStatus())%></span></td><td><%=df.format(t.getIssuedAt())%></td><td class="ticket-actions">
    <%if(b.isActive()&&"ISSUED".equals(t.getTicketStatus())){%><details><summary>Edit ticket</summary><form method="post" action="<%=cp%>/admin/tickets" class="ticket-edit" data-validate><%@ include file="/WEB-INF/jspf/csrf.jspf" %><input type="hidden" name="action" value="update"><input type="hidden" name="bookingId" value="<%=b.getBookingId()%>"><label>Passenger name<input name="passengerName" required maxlength="100" value="<%=h(b.getPassengerName())%>"></label><label>Passport / ID<input name="passportNo" required maxlength="20" value="<%=h(b.getPassportNo())%>"></label><label>Seat<input name="seatNumber" required maxlength="4" value="<%=h(b.getSeatNumber())%>"></label><small>The linked reservation is updated too, keeping the ticket consistent.</small><button class="btn btn-navy small" type="submit">Save changes</button></form></details><%}%>
    <form method="post" action="<%=cp%>/admin/tickets" data-confirm="Delete this ticket document? The reservation will remain in the system."><%@ include file="/WEB-INF/jspf/csrf.jspf" %><input type="hidden" name="action" value="delete"><input type="hidden" name="bookingId" value="<%=b.getBookingId()%>"><button class="btn btn-danger small" type="submit">Delete ticket</button></form>
  </td></tr><%}}if(!any){%><tr><td colspan="8" class="empty">No issued tickets found. Passengers can issue a ticket by using Mark Paid &amp; View Ticket.</td></tr><%}%>
  </tbody></table></div>
</main><%@ include file="/WEB-INF/jspf/footer.jspf" %></body></html>
