<%@ page contentType="text/html;charset=UTF-8" %><%@ page import="com.lankawings.model.Booking" %>
<!doctype html><html lang="en"><head><title>Payment | Lanka Wings</title><%@ include file="/WEB-INF/jspf/head.jspf" %></head><body class="app-page"><%@ include file="/WEB-INF/jspf/header.jspf" %>
<main class="container narrow page-pad"><div class="page-title"><span class="eyebrow navy">SECURE CHECKOUT</span><h1>Complete payment</h1></div><% if(err!=null){%><div class="alert error" role="alert"><%=h(err)%></div><%}%>
<% Booking b=(Booking)request.getAttribute("booking"); if(b!=null&&b.isActive()){String selected=request.getParameter("method")==null?"Visa":request.getParameter("method");%>
<div class="booking-layout"><section class="panel"><div class="cc-scene"><div class="cc-card"><div class="cc-face cc-front"><div class="cc-top"><span class="cc-chip"></span><span class="cc-brand">CARD</span></div><div class="cc-number">•••• •••• •••• ••••</div><div class="cc-bottom"><div><small>CARDHOLDER</small><span class="cc-name">FULL NAME</span></div><div><small>EXPIRES</small><span class="cc-exp">MM/YY</span></div></div></div><div class="cc-face cc-back"><div class="cc-stripe"></div><div class="cc-cvv">•••</div><div class="cc-note">Security code</div></div></div></div>
<div class="secure-note">🔒 Academic payment simulation. Only the last 4 digits are stored. Full card number, CVV and expiry are validated in memory and discarded.</div>
<form method="post" data-validate autocomplete="on"><%@ include file="/WEB-INF/jspf/csrf.jspf" %><input type="hidden" name="bookingId" value="<%=b.getBookingId()%>"><div class="pay-methods" role="radiogroup" aria-label="Payment method"><% for(String m:new String[]{"Visa","Mastercard","Debit Card"}){%><label><input type="radio" name="method" value="<%=m%>" <%=m.equals(selected)?"checked":""%>> <b><%=m%></b></label><%}%></div>
<label>Cardholder name<input id="cardHolder" name="cardHolder" data-rule="cardholder" required maxlength="60" autocomplete="cc-name" placeholder="Name on card" value="<%=h(request.getParameter("cardHolder"))%>"></label><label>Card number<input id="cardNumber" name="cardNumber" data-rule="cardnumber" data-method="input[name=method]" required inputmode="numeric" maxlength="19" autocomplete="cc-number" placeholder="4242 4242 4242 4242" data-hint="16 digits"></label><div class="form-grid"><label>Expiry<input id="expiry" name="expiry" data-rule="expiry" required inputmode="numeric" maxlength="5" autocomplete="cc-exp" placeholder="MM/YY"></label><label>CVV<input id="cvv" name="cvv" data-rule="cvv" type="password" required inputmode="numeric" maxlength="3" autocomplete="cc-csc" placeholder="•••" data-hint="3 digits"></label></div>
<div class="demo-cards"><b>Demo cards:</b> <code>4242 4242 4242 4242</code> Visa approved · <code>5555 5555 5555 4444</code> Mastercard approved · <code>4000 0000 0000 0002</code> declined.</div><button class="btn btn-orange full" type="submit">🔒 Pay LKR <%=String.format("%,.2f",b.getFare())%></button></form></section>
<aside class="trip-summary"><span class="eyebrow">PAYMENT SUMMARY</span><h2><%=h(b.getPnr())%></h2><p><%=h(b.getOrigin())%> → <%=h(b.getDestination())%></p><hr><div class="summary-line"><span>Flight</span><b><%=h(b.getFlightNo())%></b></div><div class="summary-line"><span>Passenger</span><b><%=h(b.getPassengerName())%></b></div><div class="summary-line"><span>Seat</span><b><%=h(b.getSeatNumber())%></b></div><div class="summary-line total"><span>Total</span><b>LKR <%=String.format("%,.2f",b.getFare())%></b></div></aside></div>
<% } else if(b!=null){%><a class="btn btn-outline" href="<%=cp%>/dashboard">Back to payment dashboard</a><%}%></main><%@ include file="/WEB-INF/jspf/footer.jspf" %></body></html>
